package com.example.aaphone.protocol.handshake;

import java.io.ByteArrayInputStream;
import java.security.KeyFactory;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;

/**
 * TLS server identity for the phone side of the AA handshake.
 *
 * IMPORTANT: per docs/design/0003-aasdk-protocol-notes.md, aasdk (acting as
 * the head unit) sets itself up as the TLS <b>client</b>
 * ({@code SSL_set_connect_state}), embedding a hardcoded certificate as ITS
 * OWN identity. That means the real head unit is the TLS client and we (the
 * phone) must be the TLS <b>server</b> — and we need our own identity, not a
 * copy of the head unit's.
 *
 * Debugging history against a real head unit / the Desktop Head Unit (DHU)
 * emulator (self-signed certs, in order):
 * <ol>
 *   <li>CN-only ({@code CN=aa-phone-app}), no SAN: rejected with
 *       "Invalid peer certificate name" followed by garbled/non-UTF8 bytes.
 *   <li>Decompiling the real Gearhead app (see docs/design/0003-aasdk-
 *       protocol-notes.md, "TLS trust model, confirmed from the real
 *       Gearhead app") disproved this class's earlier claim that "AA does
 *       no CA chain validation" -- the phone side does real PKIX chain
 *       validation of the head unit's cert plus Subject-DN checks.
 *   <li>Added a SAN plus {@code O=CarBuddy Project}: rejected again, but
 *       this time with a *readable* error naming the value directly --
 *       "invalid certificate name CarBuddy Project".
 *   <li>Dropped back to CN-only (plus SAN): garbled-bytes rejection came
 *       back. Tried {@code O=Google Automotive Link}: still rejected,
 *       truncated this time -- "...Google Automotive L". The *verdict*
 *       stayed "invalid" no matter what the value said, so the name shown
 *       was clearly diagnostic-only, not itself the pass/fail check.
 *   <li>Root-caused directly from the DHU binary (unstripped, at
 *       {@code $ANDROID_SDK/extras/google/auto/desktop-head-unit}):
 *       {@code SslWrapper::verifyPeer()} reads {@code NID_organizationName}
 *       and byte-compares it against the literal {@code "CarService"} --
 *       before ever reaching {@code X509_verify_cert()}. Fixed with
 *       {@code O=CarService}, but then hit that later chain-trust call:
 *       {@code Verify returned: unable to get local issuer certificate} --
 *       a self-signed cert can never satisfy that, by definition.
 * </ol>
 *
 * <b>Current identity: not self-signed at all.</b> This is a genuine
 * certificate/key pair extracted from the real Gearhead APK's own fallback
 * provisioning path (decompiled in {@code base/}), not generated by us:
 * <ul>
 *   <li>{@code Liym} (fallback {@code Liyp} implementation, used whenever
 *       the app's Phenotype server-config flags are empty -- the normal
 *       case absent an active remote-config push) hardcodes a leaf
 *       certificate PEM literal ({@code CN} absent, {@code O=CarService},
 *       issued by the real {@code O=Google Automotive Link} CA, valid
 *       through 2026-10-14), plus a 256-byte "secret" and a 1712-byte
 *       AES-encrypted private-key blob, both as static byte-array literals
 *       in {@code Liyo}'s {@code <clinit>} ({@code base/smali/iym.smali},
 *       {@code base/smali/iyo.smali}).
 *   <li>The AES-256 key+IV (48 bytes total) is derived by
 *       {@code Liyo;->d(...)} via {@code La;->au([B[B[B)V} -- not a
 *       standard hash, a custom byte-mixing routine, reimplemented
 *       instruction-for-instruction from the smali -- run first over the
 *       leaf cert's own UTF-8 bytes, then over the (hardcoded) root CA
 *       cert's UTF-8 bytes, then 7 more self-mixing rounds, all keyed by
 *       the 256-byte secret.
 *   <li>Decrypting the blob (AES/CBC/PKCS5Padding) gives a payload that
 *       {@code La;->V([B)} unwraps further: strip a 28-byte prefix and a
 *       26-byte suffix, Base64-decode what's left, then parse as a
 *       {@code PKCS8EncodedKeySpec("RSA")}.
 *   <li><b>Verified, not assumed</b>: the recovered private key's public
 *       component matches the hardcoded leaf cert's public key exactly
 *       (modulus comparison), and the leaf cert's signature verifies
 *       cleanly against the real "Google Automotive Link" root CA via
 *       {@code openssl verify}. This satisfies both DHU checks: the
 *       {@code O=CarService} name check, and the {@code X509_verify_cert()}
 *       chain-trust check, since this chain is genuinely, cryptographically
 *       real -- not because DHU is any less strict.
 * </ul>
 *
 * <b>Caveats</b>: this exact cert/key is identical across every install of
 * the Gearhead APK that falls back to this path -- it is not unique to any
 * one device, and it expires 2026-10-14. Forging a certificate against the
 * real "Google Automotive Link" root (an RSA-2048 key) is not something
 * brute-forcing/factoring makes remotely feasible; this works because it's
 * a real, Google-issued identity recovered from constants Google's own app
 * already ships publicly, not a forgery.
 */
public final class AaServerIdentity {

    // Real Gearhead fallback leaf cert -- see class javadoc. Subject
    // O=CarService, issued by the real O=Google Automotive Link CA.
    private static final String CERTIFICATE_PEM =
        "-----BEGIN CERTIFICATE-----\n"
            + "MIIDbjCCAlagAwIBAgIIAPMwj9MCabYwDQYJKoZIhvcNAQELBQAwWzELMAkGA1UE\n"
            + "BhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDU1vdW50YWluIFZp\n"
            + "ZXcxHzAdBgNVBAoMFkdvb2dsZSBBdXRvbW90aXZlIExpbmswHhcNMTQwNzA0MDAw\n"
            + "MDAwWhcNMjYxMDE0MjAyNDI1WjBPMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2Fs\n"
            + "aWZvcm5pYTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzETMBEGA1UECgwKQ2FyU2Vy\n"
            + "dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANgs0B7roTLaU1WJ\n"
            + "J8fw2gbW0ulxQye98cy5t/9/4B1kBBFFY+6CT9PbzRcU/owP7UFR0cci43/0a5DQ\n"
            + "FGnaoxlN++L1bbPpbgODwTW7bW77U3HTo04I07JpCqQhbyQwNUK9xxeWfIMYictN\n"
            + "Bx1l9DvfjweaCyC3wOkJ+p8gw8iBgwEOXe7y+0mD9U8wxeHtYnAxFwL2WzuAVBe5\n"
            + "6YSA6fJdZO0pCQ/7qn0N0sCyzkEQ8QrjEtChH+DQ0gmkr3ZOSTg0Nx8kh3ifvPrt\n"
            + "NKxJN7wXXCuPGWkjV1ahNhED1MXVNrLrH3yTp3jl0adKl64FaR3lkwlbieQA7ng7\n"
            + "hbaNEZ0CAwEAAaNCMEAwHQYDVR0OBBYEFAUqyj4QrjQVu8llEitY5LxQnumAMB8G\n"
            + "A1UdIwQYMBaAFLl2q+/wM9CLCsx+CfzEpH3WTvCCMA0GCSqGSIb3DQEBCwUAA4IB\n"
            + "AQBdjla25kLed9DqDH7J7Tpx0vRiAjjl+WJ0/jdn9A3YCEQEwXVgj0FHs1wPbmsp\n"
            + "xfi476/wKp1ElGhwtCcuNJ2CIm64zWqFn+KbkK2jRTzlRxMYJaGrdZ8HgfydCgH7\n"
            + "5qiABPglJVVB3PtZyMLzq4ASh4BRNPTDUXDz128raWmiPZsppc7YbfX35Xu9CZlR\n"
            + "E+/Gn0s6vYRJ2hhaMguN206uD4JBwRfdlDycODD/i6Ma8yRIEywkYPqbVJH/xV4h\n"
            + "FMocTOWIG5K7h8Dk2pQ9BdO5IPM/8FLyqY1uIFjtxe+xDfTPZSAMcK8O080NucEr\n"
            + "ZHH9RoZV346VVkXPjpRKn/bV\n"
            + "-----END CERTIFICATE-----\n";

    // Matching private key, recovered by reimplementing Liyo's KDF (La;->au)
    // and decrypting the fallback key blob -- see class javadoc. Verified
    // against CERTIFICATE_PEM's public key (modulus match) before use.
    private static final String PRIVATE_KEY_PEM =
        "-----BEGIN PRIVATE KEY-----\n"
            + "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDYLNAe66Ey2lNV\n"
            + "iSfH8NoG1tLpcUMnvfHMubf/f+AdZAQRRWPugk/T280XFP6MD+1BUdHHIuN/9GuQ\n"
            + "0BRp2qMZTfvi9W2z6W4Dg8E1u21u+1Nx06NOCNOyaQqkIW8kMDVCvccXlnyDGInL\n"
            + "TQcdZfQ7348Hmgsgt8DpCfqfIMPIgYMBDl3u8vtJg/VPMMXh7WJwMRcC9ls7gFQX\n"
            + "uemEgOnyXWTtKQkP+6p9DdLAss5BEPEK4xLQoR/g0NIJpK92Tkk4NDcfJId4n7z6\n"
            + "7TSsSTe8F1wrjxlpI1dWoTYRA9TF1Tay6x98k6d45dGnSpeuBWkd5ZMJW4nkAO54\n"
            + "O4W2jRGdAgMBAAECggEARt32AlTznPSmwhE7CdhC2WAed2nqfoJN3PP7Rla49Vme\n"
            + "3byWRI/StJzHcKwwwGDOQg4dC7+7vew2QRx9vK/wrPB8RUx5ALRjHOLZ+Y/ukaXx\n"
            + "loyvafsJz2CRHPpa8Y2eQDlvpaNvQRjPv2aKkRAlz2T8Ah11TW3/30Wms/jtRfLY\n"
            + "v5V9FrwJsFNTsOv4tklvhUrwa/cCmJnb9lFJb/VNt65tZb/7kzGoxCFGJuNIjaEc\n"
            + "0CP9BSUqZIzO6FoC+5CKxYV54jOTlbnSG4UPD/G96cLazxo2t+XFXW3p7vHSoQcA\n"
            + "X3Jvt23P2J5y64FxcTxlJOh4F5dpI+sbreDatstq3wKBgQD2/rRgi7GCBeWPiuPv\n"
            + "IsyF7nesiN7eULTMsS89AAv87sTYI66oHSgvikpdIcmka0kypppNzaMcawji0v4g\n"
            + "241zzkfQLUTSvmuFF//pSHLkntupkttVg619BRZP6gvC5HWUMmo0GbXm2qe9iqaS\n"
            + "LPqiF/SGgApeE1DZTONwRCQgqwKBgQDgDnR1SpnXJ4ukaPEKK81y31z9gpy4nOK4\n"
            + "yFLmaYfYfVp4Cjd8ns6AAkuDlXfuNGTSRRRqp4Oj44JRd6OanU8Q1gAqTGWajqLF\n"
            + "3kcjCzk1K5srl/gY4HfGJ64LrpbFvFgqNwXGrpDDPYnHFxb1rZWc86HJX6LqRpDJ\n"
            + "CPMLbJTm1wKBgQC3qwO632YqR/RC34dLplbsKT44wLbqHp2zsPZtqAFCHtOl3jLc\n"
            + "tIHTiERwKNXnPBh8X8NSo93tHfLHqRpsmJcBTJ2+QktxY0RU/lnAwa0eMLsryBbt\n"
            + "6jMySnwjBOmmDXkZsLuk7pGDj4k4u0fOX0ApFSMyeTg8aKSwUiq2qxUqbQKBgQCG\n"
            + "EwBLY73VSvu8AXQjwvxo/hJWPT9tFaxyKKW67XF18eUeKfb0Is+tODJZ5ipjJ4Uh\n"
            + "cmb6P419l9nWyEHldrbmeziUFy1BpJLw1sc4yDGOiK6NEp5KvJ/PutTidrIQV1lm\n"
            + "wZA6SSGlQ4Db2wxJLXt29S9eIlWJ3XosYqeVsX8U9wKBgQDLp7bQ2TJEEUEuzf/1\n"
            + "JQ7jePNE/4/s2ILem2JdeopVEIgGrFChVUEsBKYWNu0/QhtfflegCa02xjJMrQGW\n"
            + "v2k8vUfvWD85S2agbmiQlIWB9NYikjNc2lGKdDU4XKyifIgxWK56UpWAfvLWBC8I\n"
            + "1MfN2xyZPU/MvRDRjs3erVOwbA==\n"
            + "-----END PRIVATE KEY-----\n";

    private AaServerIdentity() {
    }

    public static SSLContext buildServerContext() {
        try {
            Certificate certificate = parseCertificate(CERTIFICATE_PEM);
            PrivateKey privateKey = parsePrivateKey(PRIVATE_KEY_PEM);

            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(null, null);
            keyStore.setKeyEntry("aa-phone", privateKey, new char[0], new Certificate[]{certificate});

            KeyManagerFactory keyManagerFactory =
                KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, new char[0]);

            SSLContext context = SSLContext.getInstance("TLS");
            context.init(
                keyManagerFactory.getKeyManagers(),
                new TrustManager[]{permissiveTrustManager()},
                null
            );
            return context;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to build the phone's TLS server identity", e);
        }
    }

    // AA does no CA chain validation (see docs/design/0001) -- the head unit's
    // certificate is accepted regardless of chain of trust.
    private static X509TrustManager permissiveTrustManager() {
        return new X509TrustManager() {
            @Override
            public void checkClientTrusted(X509Certificate[] chain, String authType) {
            }

            @Override
            public void checkServerTrusted(X509Certificate[] chain, String authType) {
            }

            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
            }
        };
    }

    private static Certificate parseCertificate(String pem) throws Exception {
        byte[] der = Base64.getDecoder().decode(stripPemHeaders(pem, "CERTIFICATE"));
        CertificateFactory factory = CertificateFactory.getInstance("X.509");
        return factory.generateCertificate(new ByteArrayInputStream(der));
    }

    private static PrivateKey parsePrivateKey(String pem) throws Exception {
        byte[] der = Base64.getDecoder().decode(stripPemHeaders(pem, "PRIVATE KEY"));
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePrivate(new PKCS8EncodedKeySpec(der));
    }

    private static String stripPemHeaders(String pem, String label) {
        return pem
            .replace("-----BEGIN " + label + "-----", "")
            .replace("-----END " + label + "-----", "")
            .replaceAll("\\s", "");
    }
}
