plugins {
    id 'com.android.library'
    id 'jacoco'
}
android {
    namespace 'com.example.aaphone.protocol'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        minSdk 35
        targetSdk 37

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            enableUnitTestCoverage true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    testImplementation libs.junit
    testImplementation libs.mockito.core
    implementation libs.apache.commons
}

jacoco {
    toolVersion = "0.8.15"
}

tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn 'testDebugUnitTest'
    reports {
        xml.required = true
        html.required = true
    }
    def fileFilter = [
        '**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*',
        '**/*Test*.*', 'android/**/*.*'
    ]
    def javacClasses = fileTree(
        dir: "$buildDir/intermediates/javac/debug/compileDebugJavaWithJavac/classes",
        excludes: fileFilter)
    classDirectories.setFrom(files([javacClasses]))
    sourceDirectories.setFrom(files(["$projectDir/src/main/java"]))
    executionData.setFrom(fileTree(dir: buildDir, includes: [
        'jacoco/testDebugUnitTest.exec',
        'outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec'
    ]))
}
